server:
  port: 8085
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:814362@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
app:
  file:
    storage-dir: C:/upload
    download-prefix: http://localhost:8080/api/v1/file/media/download/
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

