server:
  port: 8085
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:814362@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: file-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

