server:
  port: 8088
  servlet:
    context-path: /interaction

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  application:
    name: interaction-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/interaction_service?createDatabaseIfNotExist=true}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:814362}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: interaction-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    post:
      url: http://localhost:8084/post
    profile:
      url: http://localhost:8082/profile

