server:
  port: 8084
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: mongodb://root:814362@localhost:27017/post-service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: post-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  services:
    profile:
      url: http://localhost:8082/profile
    social:
      url: http://localhost:8087/social